parameters:
- name: imageName
  type: string
  default: 'bridgecrew/checkov'
- name: directoryCheckov
  type: string
  default: 'terraform'
- name: skipCheck
  type: string
  default: 'none'
- name: workingDirectory
  type: string
- name: testResultsFileName
  type: string
- name: dependsOn
  type: string
- name: environment
  type: string
#- name: privatePoolName
#  type: string
- name: tfVersion
  type: string
- name: serviceConnection
  type: string
- name: backendResourceGroupName
  type: string
- name: backendStorageAccountName
  type: string
- name: backendContainerName
  type: string
- name: checkFormat
  type: boolean
- name: infracostDependsOn
  type: string
- name: infracostBudget
  type: number

stages:
- stage: build
  displayName: "Build and Test"
  jobs:
    - template: checkov.yml
      parameters:
        workingDirectory: ${{ parameters.workingDirectory }}
        imageName: ${{ parameters.imageName }}
        testResultsFileName: ${{ parameters.testResultsFileName }}
        directoryCheckov: ${{ parameters.directoryCheckov}}
        skipCheck: ${{ parameters.skipCheck }}
    - template: build.yml
      parameters:
        dependsOn: ${{ parameters.dependsOn }}
        environment: ${{ parameters.environment }}
#        privatePoolName: ${{ parameters.privatePoolName }}
        tfVersion: ${{ parameters.tfVersion }}
        workingDirectory: ${{ parameters.workingDirectory }}
        serviceConnection: ${{ parameters.serviceConnection }}
        backendResourceGroupName: ${{ parameters.backendResourceGroupName}}
        backendStorageAccountName: ${{ parameters.backendStorageAccountName }}
        backendContainerName: ${{ parameters.backendContainerName}}
        checkFormat: ${{ parameters.checkFormat }}
    - template: infracost.yml
      parameters:
        environment: ${{ parameters.environment }}
        dependsOn: ${{ parameters.infracostDependsOn }}
        infracostBudget: ${{ parameters.infracostBudget }}
    - template: tfsec.yml
      parameters:
        environment: ${{ parameters.environment }}
