parameters:
- name: workingDirectory
  type: string
- name: checkovImageName
  type: string
- name: checkovTestResultsFileName
  type: string
- name: scanDirectory
  type: string
- name: skipCheck
  type: string


jobs:
  - job: "runCheckov"
    displayName: "Checkov > Pull, run and publish results of Checkov scan"
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: |
          docker pull ${{ parameters.checkovImageName }}
        workingDirectory: ${{ parameters.workingDirectory }}
        displayName: "Pull > bridgecrew/checkov"
      - bash: |
          docker run \
            --volume $(pwd):/${{ parameters.scanDirectory }} ${{ parameters.checkovImageName }} \
            --directory /${{ parameters.scanDirectory }} \
            --output junitxml \
            --soft-fail > $(pwd)/${{ parameters.checkovTestResultsFileName }} \
            --skip-check ${{ parameters.skipCheck }}          
        workingDirectory: ${{ parameters.workingDirectory }}
        displayName: "Run > checkov"
      - task: PublishTestResults@2
        inputs:
          testRunTitle: "Checkov Results"
          failTaskOnFailedTests: false # change to true for production
          testResultsFormat: "JUnit"
          testResultsFiles: ${{ parameters.checkovTestResultsFileName }}
          searchFolder: ${{ parameters.workingDirectory }}
        displayName: "Publish > Checkov scan results"