parameters:
- name: workingDirectory
  type: string
- name: imageName
  type: string
- name: testResultsFileName
  type: string
- name: directoryCheckov
  type: string
- name: skipCheck
  type: string


jobs:
  - job: "runCheckov"
    displayName: "Checkov > Pull, run and publish results of Checkov scan"
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: |
          docker pull ${{ parameters.imageName }}
        workingDirectory: ${{ parameters.workingDirectory }}
        displayName: "Pull > bridgecrew/checkov"
      - bash: |
          docker run \
            --volume $(pwd):/${{ parameters.directoryCheckov }} ${{ parameters.imageName }} \
            --directory /${{ parameters.directoryCheckov }} \
            --output junitxml \
            --soft-fail > $(pwd)/${{ parameters.testResultsFileName }} \
            --skip-check ${{ parameters.skipCheck }}          
        workingDirectory: ${{ parameters.workingDirectory }}
        displayName: "Run > checkov"
      - task: PublishTestResults@2
        inputs:
          testRunTitle: "Checkov Results"
          failTaskOnFailedTests: false # change to true for production
          testResultsFormat: "JUnit"
          testResultsFiles: ${{ parameters.testResultsFileName }}
          searchFolder: ${{ parameters.workingDirectory }}
        displayName: "Publish > Checkov scan results"