parameters:
- name: environment
  type: string
jobs:
  - job: ${{ parameters.environment}}tfsec
    pool:
      vmImage: ubuntu-latest
    displayName: "${{ parameters.environment }} Tfsec Analysis"
    steps:
      - bash: |
          mkdir reports
          chmod a+w reports

          docker run -v "$(pwd):/tf" -v "$(pwd)/reports:/reports" aquasec/tfsec /tf --format junit --out /reports/tfsec.xml -s

        workingDirectory: $(System.DefaultWorkingDirectory)/
        displayName: "Run > tfsec"
      - task: PublishTestResults@2
        inputs:
          testRunTitle: "Tfsec Results"
          failTaskOnFailedTests: false # change to true for production
          testResultsFiles: '**/reports/tfsec.xml' 
        displayName: "Publish > Tfscan scan results"